[2023-10-11T03:43:05.190+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_sql_dag.check_connect_to_db manual__2023-10-11T03:43:01.107966+00:00 [queued]>
[2023-10-11T03:43:05.202+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_sql_dag.check_connect_to_db manual__2023-10-11T03:43:01.107966+00:00 [queued]>
[2023-10-11T03:43:05.204+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-11T03:43:05.220+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): check_connect_to_db> on 2023-10-11 03:43:01.107966+00:00
[2023-10-11T03:43:05.228+0000] {standard_task_runner.py:57} INFO - Started process 121 to run task
[2023-10-11T03:43:05.232+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_sql_dag', 'check_connect_to_db', 'manual__2023-10-11T03:43:01.107966+00:00', '--job-id', '992', '--raw', '--subdir', 'DAGS_FOLDER/etl_sql_dag.py', '--cfg-path', '/tmp/tmpvxo9qeis']
[2023-10-11T03:43:05.238+0000] {standard_task_runner.py:85} INFO - Job 992: Subtask check_connect_to_db
[2023-10-11T03:43:05.293+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_sql_dag.check_connect_to_db manual__2023-10-11T03:43:01.107966+00:00 [running]> on host 86d6a4594349
[2023-10-11T03:43:05.388+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_sql_dag' AIRFLOW_CTX_TASK_ID='check_connect_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-10-11T03:43:01.107966+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-11T03:43:01.107966+00:00'
[2023-10-11T03:43:05.587+0000] {logging_mixin.py:151} INFO - 19.3.0.0.0
[2023-10-11T03:43:05.605+0000] {logging_mixin.py:151} INFO - connected to database successful
[2023-10-11T03:43:05.633+0000] {python.py:194} INFO - Done. Returned value was: True
[2023-10-11T03:43:05.666+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_sql_dag, task_id=check_connect_to_db, execution_date=20231011T034301, start_date=20231011T034305, end_date=20231011T034305
[2023-10-11T03:43:05.688+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-11T03:43:05.716+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
